
project_id = "xtwxemlxzbnadkkrvozr"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-latest-newsletter]
verify_jwt = false

[functions.setup-cron-job]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.cs-analyzer]
verify_jwt = false

[functions.content-access]
verify_jwt = false

[functions.cs-triage]
verify_jwt = false

[functions.cs-advisor]
verify_jwt = false
