import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { V2ReportRenderer } from "@/components/cs-analyzer/report-v2/V2ReportRenderer";
import { ReportSkeleton } from "@/components/cs-analyzer/ReportSkeleton";
import type { PipelineResult } from "@/components/cs-analyzer/report-v2/types";
import { supabase } from "@/integrations/supabase/client";
import { ArrowRight } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

interface SharedAnalysis {
  id: string;
  title: string;
  results: Record<string, unknown>;
  created_at: string;
  public_share_id: string;
}

const CSAnalyzerShare = () => {
  const { shareId } = useParams<{ shareId: string }>();
  const { user } = useAuth();
  const [analysis, setAnalysis] = useState<SharedAnalysis | null>(null);
  const [pipelineResult, setPipelineResult] = useState<PipelineResult | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    const fetchShared = async () => {
      if (!shareId) {
        setError("No share ID provided.");
        setIsLoading(false);
        return;
      }

      setIsLoading(true);
      setError(null);

      // IMPORTANT: only fetch public-safe columns. Never include input_text
      // here — the raw transcript may contain PII and isn't part of what
      // gets shared publicly.
      const { data, error: fetchError } = await supabase
        .from("analyses")
        .select("id, title, results, created_at, public_share_id, is_public")
        .eq("public_share_id", shareId)
        .eq("is_public", true)
        .maybeSingle();

      if (cancelled) return;

      if (fetchError) {
        setError("Could not load this report.");
        setIsLoading(false);
        return;
      }

      if (!data) {
        setError("This report doesn't exist or is no longer public.");
        setIsLoading(false);
        return;
      }

      setAnalysis(data as SharedAnalysis);

      // Parse the results JSON to extract the pipeline result
      let results = data.results as Record<string, unknown>;
      if (typeof results?.content === "string") {
        try {
          const parsed = JSON.parse(results.content as string);
          if (typeof parsed === "object" && parsed !== null) {
            results = parsed as Record<string, unknown>;
          }
        } catch {
          // not JSON — older v1 report, won't render properly here
        }
      }

      if (results?.reportVersion === "v2_panel" && results?.pipelineResult) {
        setPipelineResult(results.pipelineResult as PipelineResult);
      } else {
        setError("This report uses a legacy format and can't be viewed publicly.");
      }

      setIsLoading(false);

      // SEO: set page title
      if (data.title) {
        document.title = `${data.title} | CS Analyzer | Churn Is Dead`;
      }
    };

    fetchShared();
    return () => {
      cancelled = true;
    };
  }, [shareId]);

  const runCtaHref = user ? "/cs-analyzer" : "/auth?from=/cs-analyzer";
  const runCtaLabel = user ? "Run your own analysis" : "Sign in to run your own";

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1">
        {/* Banner */}
        <section className="border-b border-navy-dark/10 bg-cream/40">
          <div className="max-w-5xl mx-auto px-4 md:px-6 py-6 flex items-center justify-between gap-4 flex-wrap">
            <div>
              <p className="text-[10px] uppercase tracking-[0.22em] text-red font-bold mb-1">
                Shared Report
              </p>
              <p className="text-sm text-muted-foreground">
                Generated by the <Link to="/cs-analyzer" className="text-navy-dark font-semibold underline-offset-2 hover:underline">CS Analyzer</Link> at churnisdead.com
              </p>
            </div>
            <Link
              to={runCtaHref}
              className="inline-flex items-center gap-2 py-2 px-4 bg-red text-white text-sm font-semibold rounded-lg hover:bg-red-dark transition-colors"
            >
              {runCtaLabel}
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </section>

        {/* Body */}
        <section className="bg-background">
          <div className="max-w-5xl mx-auto px-4 md:px-6 py-8 md:py-12">
            {isLoading && <ReportSkeleton />}

            {error && !isLoading && (
              <div className="max-w-xl mx-auto text-center py-20">
                <p className="text-[10px] uppercase tracking-[0.22em] text-red font-bold mb-3">
                  Not Available
                </p>
                <h1 className="text-2xl md:text-3xl font-serif font-black text-navy-dark mb-3 leading-tight">
                  {error}
                </h1>
                <p className="text-muted-foreground mb-6">
                  The owner of this report may have unshared it. You can still try the analyzer yourself.
                </p>
                <Link
                  to={runCtaHref}
                  className="inline-flex items-center gap-2 py-2.5 px-5 bg-red text-white text-sm font-semibold rounded-lg hover:bg-red-dark transition-colors"
                >
                  {runCtaLabel}
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            )}

            {!isLoading && !error && analysis && pipelineResult?.finalReport && (
              <V2ReportRenderer
                report={pipelineResult.finalReport}
                evidenceAnchors={pipelineResult.evidenceAnchors || []}
                title={analysis.title}
                createdAt={analysis.created_at}
              />
            )}
          </div>
        </section>

        {/* Bottom CTA */}
        {!isLoading && !error && (
          <section className="border-t border-navy-dark/10 bg-navy-dark text-white">
            <div className="max-w-3xl mx-auto px-4 md:px-6 py-12 md:py-16 text-center">
              <h2 className="text-2xl md:text-3xl font-serif font-black mb-3 leading-tight">
                Want a report like this on your accounts?
              </h2>
              <p className="text-white/70 mb-6 max-w-xl mx-auto">
                Paste a call transcript. The five-agent pipeline reads every line, anchors every claim to a quote, and gives you the report you'd write if you had three more hours.
              </p>
              <Link
                to={runCtaHref}
                className="inline-flex items-center gap-2 py-3 px-6 bg-red text-white text-sm font-semibold rounded-lg hover:bg-red-dark transition-colors"
              >
                {runCtaLabel}
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </section>
        )}
      </main>

      <Footer />
    </div>
  );
};

export default CSAnalyzerShare;
