// ============================================================================
// Deterministic HTML Report Builder — Enterprise Template v2
// Generates print-ready HTML from the frozen report JSON snapshot.
// No AI dependency — instant, deterministic, matching design spec exactly.
// ============================================================================

import { getEnterpriseCss } from "./template-css.ts";

// ─── Helpers ────────────────────────────────────────────────────────────────

function esc(s: unknown): string {
  const str = String(s ?? "");
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  } catch {
    return iso;
  }
}

function formatCallType(raw: string): string {
  return raw
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function shouldShow(
  vis: Record<string, boolean>,
  si: Record<string, boolean>,
  key: string,
): boolean {
  const alwaysVisible = [
    "executive_snapshot",
    "risks_and_threats",
    "action_plan_14_days",
  ];
  if (alwaysVisible.includes(key)) return true;
  return si[key] !== false && vis[key] !== false;
}

function confidenceDot(level: string): string {
  const cls =
    level === "high"
      ? "confidence-high"
      : level === "medium"
        ? "confidence-medium"
        : "confidence-low";
  return `<span class="confidence-dot ${cls}"></span>`;
}

function confidenceBadge(level: string): string {
  const label = (level || "unknown").charAt(0).toUpperCase() + (level || "unknown").slice(1);
  const cls =
    level === "high"
      ? "badge-success"
      : level === "medium"
        ? "badge-warning"
        : "badge-neutral";
  return `<span class="badge ${cls}" style="white-space:nowrap;">${confidenceDot(level)} ${esc(label)}</span>`;
}

function threatBadgeClass(threat: string): string {
  if (["churn", "displacement"].includes(threat)) return "badge-danger";
  if (["delay", "downsell"].includes(threat)) return "badge-warning";
  if (threat === "none") return "badge-success";
  return "badge-neutral";
}

function severityClass(sev: string): string {
  if (sev === "critical") return "sev-critical";
  if (sev === "high") return "sev-high";
  if (sev === "medium") return "sev-medium";
  return "sev-low";
}

function categoryClass(cat: string): string {
  const map: Record<string, string> = {
    adoption: "cat-adoption",
    value: "cat-value",
    incident: "cat-incident",
    budget: "cat-budget",
    stakeholder: "cat-stakeholder",
    political: "cat-political",
  };
  return map[cat?.toLowerCase()] || "cat-adoption";
}

function powerBadgeClass(power: string): string {
  if (power === "high") return "badge-danger";
  if (power === "medium") return "badge-warning";
  return "badge-neutral";
}

function stanceBadgeClass(stance: string): string {
  if (stance === "supportive") return "badge-success";
  if (["skeptical", "resistant"].includes(stance)) return "badge-danger";
  return "badge-neutral";
}

function threatColor(threat: string): string {
  if (["churn", "displacement"].includes(threat)) return "var(--brand-danger)";
  if (["delay", "downsell"].includes(threat)) return "var(--brand-warning)";
  if (threat === "none") return "var(--brand-success)";
  return "var(--brand-neutral)";
}

function sevLabel(sev: string): string {
  if (sev === "critical") return "Crit";
  if (sev === "high") return "High";
  if (sev === "medium") return "Med";
  return "Low";
}

// ─── Page structure ─────────────────────────────────────────────────────────

function pageHeader(customer: string, date: string): string {
  return `<div class="page-header">
    <div class="page-header-brand">
      <div class="page-header-logo">CD</div>
      <span class="page-header-title">Churn Is Dead &mdash; CS Intelligence</span>
    </div>
    <div class="page-header-meta">${esc(customer)}<br>${esc(date)}</div>
  </div>`;
}

function pageFooter(n: number): string {
  return `<div class="page-footer">
    <span>Confidential &mdash; Internal Use Only</span>
    <span>Generated by CS Analyzer</span>
    <span>Page ${n}</span>
  </div>`;
}

function sectionHeader(
  abbr: string,
  bg: string,
  fg: string,
  title: string,
  subtitle: string,
  badge?: string,
): string {
  return `<div class="section-header">
    <div class="section-icon" style="background:${bg};color:${fg};">${abbr}</div>
    <div>
      <div class="section-title">${esc(title)}</div>
      ${subtitle ? `<div class="section-subtitle">${esc(subtitle)}</div>` : ""}
    </div>
    ${badge ? `<div style="margin-left:auto;">${badge}</div>` : ""}
  </div>`;
}

// ─── Page builders ──────────────────────────────────────────────────────────

// deno-lint-ignore no-explicit-any
function buildCoverPage(customer: string, callType: string, date: string, n: number, report: any): string {
  return `<div class="page">
  <div class="cover">
    <div class="cover-badge">Churn Is Dead &mdash; CS Intelligence</div>
    <div class="cover-title">Executive Diagnostic Report</div>
    <div class="cover-subtitle">Transcript analysis and strategic recommendations for the ${esc(customer)} account.</div>
    <div class="cover-meta-grid">
      <div class="cover-meta-item">
        <span class="cover-meta-label">Customer</span>
        <span class="cover-meta-value">${esc(customer)}</span>
      </div>
      <div class="cover-meta-item">
        <span class="cover-meta-label">Call Type</span>
        <span class="cover-meta-value">${esc(callType)}</span>
      </div>
      <div class="cover-meta-item">
        <span class="cover-meta-label">Date Analysed</span>
        <span class="cover-meta-value">${esc(date)}</span>
      </div>
      <div class="cover-meta-item">
        <span class="cover-meta-label">Quality Score</span>
        <span class="cover-meta-value">${report?.meta?.transcript_quality_score_0_to_100 ?? "N/A"}/100</span>
      </div>
    </div>
    <div class="cover-classification">Confidential &mdash; Internal Use Only</div>
  </div>
  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildSnapshotPage(report: any, customer: string, date: string, n: number): string {
  const snap = report.executive_snapshot;
  const threat = snap?.primary_threat || "unknown";
  const threatLabel = formatCallType(threat);
  const badgeClass = threatBadgeClass(threat);

  const takeawaysHtml = (snap?.top_3_takeaways || [])
    .map(
      // deno-lint-ignore no-explicit-any
      (t: any, idx: number) => `
    <div class="takeaway-item no-break">
      <div class="takeaway-num">${idx + 1}</div>
      <div>
        <div class="takeaway-text">${esc(t.takeaway)}</div>
        <div class="takeaway-confidence">${confidenceDot(t.confidence)} ${esc(t.confidence?.charAt(0).toUpperCase() + t.confidence?.slice(1))} confidence</div>
      </div>
    </div>`,
    )
    .join("\n");

  return `<div class="page">
  ${pageHeader(customer, date)}

  ${sectionHeader("ES", "var(--brand-accent-light)", "var(--brand-accent)", "Executive Snapshot", "Key indicators at a glance", `<span class="badge ${badgeClass}">${esc(threatLabel)} Risk</span>`)}

  <div class="snapshot-card">
    <div class="snapshot-threat-row">
      <span class="snapshot-threat-badge">Primary Threat: ${esc(threatLabel)}</span>
      ${snap?.secondary_threat ? `<span class="snapshot-threat-badge" style="opacity:0.6;">Secondary: ${esc(formatCallType(snap.secondary_threat))}</span>` : `<span class="snapshot-threat-badge" style="opacity:0.6;">Secondary: None</span>`}
    </div>
    <div class="snapshot-one-liner">${esc(snap?.one_liner || "")}</div>
  </div>

  <div class="takeaway-grid">${takeawaysHtml}</div>

  <div class="strategic-truth" style="margin-top:24px;">
    <div class="strategic-truth-label">Strategic Truth</div>
    <div class="strategic-truth-text">${esc(snap?.one_liner || "")}</div>
  </div>

  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildFactsPage(facts: any[], customer: string, date: string, n: number): string {
  const factsHtml = facts
    .map(
      // deno-lint-ignore no-explicit-any
      (f: any) => `
    <div class="fact-row no-break">
      <span class="fact-category ${categoryClass(f.category)}">${esc(f.category)}</span>
      <span class="fact-text">${esc(f.fact)}</span>
      <span style="margin-left:auto;white-space:nowrap;">${confidenceBadge(f.confidence)}</span>
    </div>`,
    )
    .join("\n");

  return `<div class="page">
  ${pageHeader(customer, date)}

  ${sectionHeader("EF", "#E8F0FE", "#1A56DB", "Evidence-Backed Facts", `${facts.length} verified facts from transcript`)}

  <div class="facts-grid">${factsHtml}</div>

  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildRisksActionsPage(report: any, customer: string, date: string, n: number): string {
  const tc = report.risks_and_threats?.threat_classification || {};
  const risks = report.risks_and_threats?.risk_items || [];
  const actions = report.action_plan_14_days || [];

  const risksHtml = risks
    .map(
      // deno-lint-ignore no-explicit-any
      (r: any) => `
    <div class="risk-card no-break">
      <div class="risk-severity ${severityClass(r.severity)}">${sevLabel(r.severity)}</div>
      <div class="risk-content">
        <div class="risk-title">${esc(r.risk)}</div>
        <div class="risk-meta">
          <span class="badge badge-neutral">${esc(formatCallType(r.type || ""))}</span>
          <span>${esc(formatCallType(r.observed_or_inferred || ""))}</span>
          <span>${confidenceDot(r.confidence)} ${esc(r.confidence)}</span>
        </div>
      </div>
    </div>`,
    )
    .join("\n");

  const actionsHtml = actions
    .map(
      // deno-lint-ignore no-explicit-any
      (a: any) => `
    <div class="action-item no-break">
      <div class="action-header">
        <div class="action-title">${esc(a.action)}</div>
        <div class="action-day">Day ${a.due_in_days}</div>
      </div>
      <div class="action-details">
        <div class="action-detail-item"><span class="action-detail-label">Owner</span><span class="action-detail-value">${esc(a.owner)}</span></div>
        <div class="action-detail-item"><span class="action-detail-label">Success Criteria</span><span class="action-detail-value">${esc(a.success_criteria)}</span></div>
        <div class="action-detail-item" style="grid-column:1/-1;"><span class="action-detail-label">Why This Matters</span><span class="action-detail-value">${esc(a.why_this_matters)}</span></div>
      </div>
    </div>`,
    )
    .join("\n");

  return `<div class="page">
  ${pageHeader(customer, date)}

  ${sectionHeader("RT", "var(--brand-danger-light)", "var(--brand-danger)", "Risks & Threat Classification", `Primary: ${formatCallType(tc.primary || "unknown")} · Secondary: ${formatCallType(tc.secondary || "none")}`)}

  <div class="threat-bar no-break">
    <div class="threat-item">
      <span class="threat-label">Primary Threat</span>
      <span class="threat-value" style="color:${threatColor(tc.primary)}">${esc(formatCallType(tc.primary || "unknown"))}</span>
    </div>
    <div class="threat-item">
      <span class="threat-label">Secondary</span>
      <span class="threat-value" style="color:${tc.secondary && tc.secondary !== "none" ? threatColor(tc.secondary) : "var(--brand-neutral)"}">${esc(formatCallType(tc.secondary || "none"))}</span>
    </div>
    <div class="threat-item">
      <span class="threat-label">Confidence</span>
      <span class="threat-value">${confidenceDot(tc.confidence)} ${esc(formatCallType(tc.confidence || ""))}</span>
    </div>
  </div>

  ${risksHtml}

  <div style="height:24px;"></div>

  ${sectionHeader("AP", "var(--brand-accent-light)", "var(--brand-accent)", "14-Day Action Plan", `${actions.length} actions anchored to key deadlines`)}

  <div class="action-timeline">${actionsHtml}</div>

  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildStakeholderExpansionPage(report: any, vis: Record<string, boolean>, si: Record<string, boolean>, customer: string, date: string, n: number): string {
  const stakeholders = report.stakeholder_power_map?.stakeholders || [];
  const summary = report.stakeholder_power_map?.summary || {};
  const expansion = report.expansion_readiness;
  const showStakeholders = shouldShow(vis, si, "stakeholder_power_map") && stakeholders.length > 0;
  const showExpansion = expansion != null;

  let stakeholdersHtml = "";
  if (showStakeholders) {
    const powerDist = summary.power_distribution || {};
    const stanceDist = summary.stance_distribution || {};
    const summaryText = `${stakeholders.length} stakeholders identified · Power: ${powerDist.high || 0} high, ${powerDist.medium || 0} medium, ${powerDist.low || 0} low · Stance: ${stanceDist.supportive || 0} supportive, ${stanceDist.skeptical || 0} skeptical, ${stanceDist.neutral || 0} neutral`;

    const cardsHtml = stakeholders
      .map(
        // deno-lint-ignore no-explicit-any
        (s: any) => {
          const roleParts = (s.name_or_title || "").split(" — ");
          const name = roleParts[0] || s.name_or_title;
          const role = roleParts[1] || s.role_in_decision || "";
          const motivation = s.motivation_or_pressure || "";
          const decisionRole = formatCallType(s.role_in_decision || "unknown");

          return `
      <div class="stakeholder-card no-break">
        <div class="stakeholder-identity">
          <div class="stakeholder-name">${esc(name)}</div>
          ${role ? `<div class="stakeholder-role">${esc(role)}</div>` : ""}
        </div>
        <div class="stakeholder-meta-grid">
          <div class="stakeholder-meta-item">
            <div class="stakeholder-meta-label">Power</div>
            <div class="stakeholder-meta-value"><span class="badge ${powerBadgeClass(s.power)}">${esc(formatCallType(s.power || ""))}</span></div>
          </div>
          <div class="stakeholder-meta-item">
            <div class="stakeholder-meta-label">Stance</div>
            <div class="stakeholder-meta-value"><span class="badge ${stanceBadgeClass(s.stance)}">${esc(formatCallType(s.stance || ""))}</span></div>
          </div>
          <div class="stakeholder-meta-item">
            <div class="stakeholder-meta-label">Decision Role</div>
            <div class="stakeholder-meta-value">${esc(decisionRole)}</div>
          </div>
          ${motivation ? `<div class="stakeholder-motivation"><strong>Motivation:</strong> ${esc(motivation)}</div>` : ""}
        </div>
      </div>`;
        },
      )
      .join("\n");

    stakeholdersHtml = `
    ${sectionHeader("SM", "#F0E8FE", "#6B21A8", "Stakeholder Power Map", summaryText)}
    <div class="stakeholder-grid">${cardsHtml}</div>`;
  }

  let expansionHtml = "";
  if (showExpansion) {
    const stages = ["no_signal", "interest", "evaluation", "negotiation", "commitment"];
    const stageLabels: Record<string, string> = {
      no_signal: "No Signal",
      interest: "Interest",
      evaluation: "Evaluation",
      negotiation: "Negotiation",
      commitment: "Commitment",
    };
    const activeStage = (expansion.stage || "").toLowerCase().replace(/\s+/g, "_");
    const activeIndex = stages.indexOf(activeStage);

    const pipelineHtml = stages
      .map((stage, i) => {
        const cls = i < activeIndex ? "passed" : i === activeIndex ? "active" : "";
        return `<div class="pipeline-stage ${cls}">${stageLabels[stage]}</div>`;
      })
      .join("");

    const gateConditions = (expansion.gate_conditions || [])
      .map(
        (g: string) =>
          `<div class="gate-item no-break"><span class="gate-icon">&bull;</span> ${esc(g)}</div>`,
      )
      .join("\n");

    const blockers = (expansion.blockers || [])
      .map(
        (b: string) =>
          `<div class="gate-item no-break" style="border-left-color:var(--brand-danger);"><span class="gate-icon" style="color:var(--brand-danger);">&bull;</span> ${esc(b)}</div>`,
      )
      .join("\n");

    expansionHtml = `
    <div style="height:28px;"></div>
    ${sectionHeader("ER", "var(--brand-accent-light)", "var(--brand-accent)", "Expansion Readiness", `${esc(expansion.stage || "Unknown")} stage`)}
    <div class="expansion-pipeline">${pipelineHtml}</div>
    ${gateConditions ? `<div class="sub-section-label">Gate Conditions</div><div class="gate-list">${gateConditions}</div>` : ""}
    ${blockers ? `<div class="sub-section-label" style="margin-top:12px;">Blockers</div><div class="gate-list">${blockers}</div>` : ""}`;
  }

  return `<div class="page">
  ${pageHeader(customer, date)}
  ${stakeholdersHtml}
  ${expansionHtml}
  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildProcurementIncidentPage(report: any, vis: Record<string, boolean>, si: Record<string, boolean>, customer: string, date: string, n: number): string {
  const showProcurement = shouldShow(vis, si, "procurement_and_timeline") && report.procurement_and_timeline;
  const showIncident = shouldShow(vis, si, "incident_impact") && report.incident_impact;

  let procurementHtml = "";
  if (showProcurement) {
    const pt = report.procurement_and_timeline;
    const timelineItems = (pt.timeline_items || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (t: any) =>
          `<div class="detail-card no-break">
        <div class="detail-card-title">${esc(t.topic || t.event || "Timeline Event")}</div>
        <div class="detail-card-meta">${esc(t.when_text)} ${confidenceBadge(t.confidence)}</div>
      </div>`,
      )
      .join("\n");

    const procRisks = (pt.procurement_risks || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (r: any) =>
          `<div class="detail-card no-break" style="border-left:3px solid var(--brand-warning);">
        <div class="detail-card-text">${esc(r.risk)}</div>
        <div class="detail-card-meta">${confidenceBadge(r.confidence)}</div>
      </div>`,
      )
      .join("\n");

    procurementHtml = `
    ${sectionHeader("PT", "var(--brand-warning-light)", "var(--brand-warning)", "Procurement & Timeline", "")}
    ${timelineItems ? `<div class="sub-section-label">Timeline Events</div>${timelineItems}` : ""}
    ${procRisks ? `<div class="sub-section-label">Procurement Risks</div>${procRisks}` : ""}`;
  }

  let incidentHtml = "";
  if (showIncident) {
    const ii = report.incident_impact;
    const summaries = (ii.incident_summary || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (s: any) =>
          `<div class="detail-card no-break">
        <div class="detail-card-text">${esc(s.summary || s.incident || "")}</div>
        <div class="detail-card-meta">${confidenceBadge(s.confidence)}</div>
      </div>`,
      )
      .join("\n");

    const impacts = (ii.customer_impact || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (i: any) =>
          `<div class="detail-card no-break" style="border-left:3px solid var(--brand-danger);">
        <div class="detail-card-text">${esc(i.impact)}</div>
        <div class="detail-card-meta">${confidenceBadge(i.confidence)}</div>
      </div>`,
      )
      .join("\n");

    incidentHtml = `
    ${showProcurement ? '<div style="height:28px;"></div>' : ""}
    ${sectionHeader("II", "var(--brand-danger-light)", "var(--brand-danger)", "Incident Impact", "")}
    ${summaries ? `<div class="sub-section-label">Incident Summary</div>${summaries}` : ""}
    ${impacts ? `<div class="sub-section-label">Customer Impact</div>${impacts}` : ""}`;
  }

  return `<div class="page">
  ${pageHeader(customer, date)}
  ${procurementHtml}
  ${incidentHtml}
  ${pageFooter(n)}
</div>`;
}

// deno-lint-ignore no-explicit-any
function buildGapsEffectivenessPage(report: any, vis: Record<string, boolean>, si: Record<string, boolean>, customer: string, date: string, n: number): string {
  const showConvGaps = shouldShow(vis, si, "conversational_gaps") && report.conversational_gaps?.length > 0;
  const showValueGaps = shouldShow(vis, si, "value_narrative_gaps") && report.value_narrative_gaps?.length > 0;
  const showCsRep = shouldShow(vis, si, "cs_rep_effectiveness") && report.cs_rep_effectiveness;

  let convGapsHtml = "";
  if (showConvGaps) {
    const gapsCards = report.conversational_gaps
      .map(
        // deno-lint-ignore no-explicit-any
        (g: any) => `
      <div class="gap-card no-break">
        <div class="gap-topic">${esc(g.missing_topic)}</div>
        <div class="gap-why">${esc(g.why_it_matters)}</div>
        <div class="gap-question">${esc(g.suggested_question)}</div>
      </div>`,
      )
      .join("\n");

    convGapsHtml = `
    ${sectionHeader("CG", "#FEF0E8", "#B45309", "Conversational Gaps", "Topics a seasoned CS leader would expect to see discussed but were absent")}
    ${gapsCards}`;
  }

  let valueGapsHtml = "";
  if (showValueGaps) {
    const vgCards = report.value_narrative_gaps
      .map(
        // deno-lint-ignore no-explicit-any
        (v: any) => `
      <div class="value-gap-card no-break">
        <div class="value-gap-text">${esc(v.gap)}</div>
        <div class="value-gap-impact">Impact on renewal: <strong style="color:var(--brand-danger);">${esc(formatCallType(v.impact_on_renewal || ""))}</strong></div>
      </div>`,
      )
      .join("\n");

    valueGapsHtml = `
    ${convGapsHtml ? '<div style="height:24px;"></div>' : ""}
    ${sectionHeader("VG", "var(--brand-warning-light)", "var(--brand-warning)", "Value Narrative Gaps", "Weaknesses in value positioning that affect renewal and expansion")}
    ${vgCards}`;
  }

  let csRepHtml = "";
  if (showCsRep) {
    const rep = report.cs_rep_effectiveness;
    const strengthsItems = (rep.strengths || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (s: any) =>
          `<div class="effectiveness-item">${esc(s.strength)}</div>`,
      )
      .join("\n");

    const gapItems = (rep.gaps || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (g: any) =>
          `<div class="effectiveness-item">${esc(g.gap)}</div>`,
      )
      .join("\n");

    const coachingCards = (rep.coaching_moves || [])
      .map(
        // deno-lint-ignore no-explicit-any
        (c: any) => `
      <div class="coaching-card no-break">
        <div class="coaching-move">${esc(c.move)}</div>
        <div class="coaching-why">${esc(c.why)}</div>
      </div>`,
      )
      .join("\n");

    csRepHtml = `
    ${convGapsHtml || valueGapsHtml ? '<div style="height:24px;"></div>' : ""}
    ${sectionHeader("RE", "#E8F0FE", "#1A56DB", "CS Rep Effectiveness", "Behavioural assessment from transcript analysis")}
    <div class="effectiveness-grid">
      <div class="effectiveness-col strengths">
        <h4>Strengths</h4>
        ${strengthsItems}
      </div>
      <div class="effectiveness-col gaps">
        <h4>Gaps</h4>
        ${gapItems}
      </div>
    </div>
    ${coachingCards ? `<div class="sub-section-label">Coaching Recommendations</div>${coachingCards}` : ""}`;
  }

  return `<div class="page">
  ${pageHeader(customer, date)}
  ${convGapsHtml}
  ${valueGapsHtml}
  ${csRepHtml}
  ${pageFooter(n)}
</div>`;
}

// ─── Main export ────────────────────────────────────────────────────────────

interface BuildParams {
  // deno-lint-ignore no-explicit-any
  report: any;
  visibility: Record<string, boolean>;
  title: string;
  finalizedAt: string;
}

export function buildReportHtml(params: BuildParams): string {
  const { report, visibility, title, finalizedAt } = params;
  const si = report.section_included || {};
  const dateStr = formatDate(
    finalizedAt || report.meta?.generated_at_iso || new Date().toISOString(),
  );
  const customer = title || "Analysis Report";
  const callType = formatCallType(report.meta?.call_type || "unknown");

  let pageNum = 1;
  const pages: string[] = [];

  // Page 1: Cover (always)
  pages.push(buildCoverPage(customer, callType, dateStr, pageNum++, report));

  // Page 2: Executive Snapshot (always)
  if (report.executive_snapshot) {
    pages.push(buildSnapshotPage(report, customer, dateStr, pageNum++));
  }

  // Page 3: Evidence Facts (conditional)
  if (
    shouldShow(visibility, si, "evidence_backed_facts") &&
    report.evidence_backed_facts?.length > 0
  ) {
    pages.push(buildFactsPage(report.evidence_backed_facts, customer, dateStr, pageNum++));
  }

  // Page 4: Risks + Actions (always)
  pages.push(buildRisksActionsPage(report, customer, dateStr, pageNum++));

  // Page 5: Stakeholders + Expansion (conditional)
  const showStakeholders =
    shouldShow(visibility, si, "stakeholder_power_map") &&
    report.stakeholder_power_map?.stakeholders?.length > 0;
  const showExpansion = report.expansion_readiness != null;
  if (showStakeholders || showExpansion) {
    pages.push(
      buildStakeholderExpansionPage(report, visibility, si, customer, dateStr, pageNum++),
    );
  }

  // Page 6: Procurement + Incident (conditional)
  const showProcurement =
    shouldShow(visibility, si, "procurement_and_timeline") &&
    report.procurement_and_timeline;
  const showIncident =
    shouldShow(visibility, si, "incident_impact") && report.incident_impact;
  if (showProcurement || showIncident) {
    pages.push(
      buildProcurementIncidentPage(report, visibility, si, customer, dateStr, pageNum++),
    );
  }

  // Page 7: Gaps + Effectiveness (conditional)
  const showConvGaps =
    shouldShow(visibility, si, "conversational_gaps") &&
    report.conversational_gaps?.length > 0;
  const showValueGaps =
    shouldShow(visibility, si, "value_narrative_gaps") &&
    report.value_narrative_gaps?.length > 0;
  const showCsRep =
    shouldShow(visibility, si, "cs_rep_effectiveness") &&
    report.cs_rep_effectiveness;
  if (showConvGaps || showValueGaps || showCsRep) {
    pages.push(
      buildGapsEffectivenessPage(report, visibility, si, customer, dateStr, pageNum++),
    );
  }

  const css = getEnterpriseCss();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(customer)} &mdash; CS Intelligence Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>${css}</style>
</head>
<body>
${pages.join("\n")}
</body>
</html>`;
}
