
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtwxemlxzbnadkkrvozr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0d3hlbWx4emJuYWRra3J2b3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTUzNDAsImV4cCI6MjA2MzAzMTM0MH0.FX3zb-zai6KIM24eW4pckqWLNIg0HFCPil8cJW7l3t4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with enhanced debugging options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'x-app-version': '1.0.0',
      },
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
